#----------------------
# About section

blurb: <p><strong>Evolutionary ecologist.</strong> I am recently graduate, now research professional. My research interests are in the areas of evolutionary biology, quantitative genetics. My doctoral disertation was on Tree swallow.</p>

#----------------------
# Courses section
courses:
  - {title: Intro to Chem, semester: Fall 1885, school: King's College London, description: Teaching students chemistry isn't only for witches., link: courses/temp_course }
  - {title: Advanced Psychiatric Medicine, semester: Spring 1885, school: King's College London, description: At the time, mainly lobotomy., link: courses/temp_course }
  - {title: Diseases of the Mind, semester: Fall 1884, school: King's College London, description: Survey course. Mainly taught by example., link: courses/temp_course }
#----------------------
# Contact
contact-info: <p>Audrey Bourret<br>Universite de Sherbrooke<br>Departement de biologie<br>Sherbrooke<br>Canada</p>

contact-links:
  - {contact-text: Github, contact-link: "https://www.google.com", icon: 'favicon.html'}
